### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by pablodawson** [TencentARC/CustomNet#3]
Great work!
Sorry to be that guy, but when are you planning to release this, maybe after CVPR submissions?

**Comment by mehdizade** [comment]
Same here

**Comment by jiangyzy** [comment]
Thanks, we are working on it now!

**Comment by tkpham3105** [comment]
Great work. Also looking forward to code release.

**Comment by kelisiya** [comment]
+1

**Comment by Njasa2k** [comment]
+1

**Comment by YIBO0408** [comment]
Niubi！
