### ISSUE TITLE
Will the checkpoint that can take background image as input be released?

### ISSUE THREAD

**Issue by co1dspring** [TencentARC/CustomNet#9]
The checkpoint provided now only has 4 input channels.

**Comment by co1dspring** [comment]
my bad

**Comment by hk341b** [comment]
@co1dspring how did you get this working again?

**Comment by SWHL** [comment]
You can refer this [repo](https://github.com/smthemex/ComfyUI_CustomNet/blob/49eb0d40ff3b46d0f04c781f61a8b6678729a417/Comfyui_CustomNet_node.py#L71-L76) which has reproduced.
